version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: unless-stopped
    networks:
      - postgres

  app:
    image: gopma-demo-1-be:latest
    container_name: app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
